### ISSUE TITLE
[Bug] Extremely lags on mobile

### ISSUE THREAD

**Issue by DerGoogler** [DerGoogler/Hentai-Web#30]
The mobile app has extreme lags, it can be unuseable! I will fix it soon. instead can you use the website: https:dergoogler.com/hentai-web

**Comment by Axe090** [comment]
Agreed, extreme lag xD

**Comment by DerGoogler** [comment]
> Agreed, extreme lag xD

Lags has been fixed, you can download the fix from [here](https://github.com/DerGoogler/Hentai-Web/releases/download/1.3.6/app-release-hotfix.apk) or from the releases. Enjoy! 😀

**Comment by Axe090** [comment]
> > Agreed, extreme lag xD
> 
> Lags has been fixed, you can download the fix from [here](https://github.com/DerGoogler/Hentai-Web/releases/download/1.3.6/app-release-hotfix.apk) or from the releases. Enjoy! 😀

Works great now. Thanks
